name: drupal-upgrade
recipe: drupal9
config:
  webroot: web
  php: '8.1'
  composer_version: '2'
  database: mariadb:10.6

services:
  appserver:
    build:
      - composer install
  pma:
    type: phpmyadmin
    hosts:
      - database